### ISSUE TITLE
newsPermafeed

### ISSUE THREAD

**Issue by crypto-guys** [AndreiD/arweave-permafeed-web#2]
Title: newsPermafeed
Author: crypto-guys
Description: News headlines updated 2x per hour
Wallet: iie7jUhFrlN4sV8UppcI7Fc5mN07XDvvgQ0R53fugcU
Code example:

{
  op: 'and',
  expr1: {
    op: 'equals',
    expr1: 'from',
    expr2: 'iie7jUhFrlN4sV8UppcI7Fc5mN07XDvvgQ0R53fugcU'
  },
  expr2: {
    op: 'equals',
    expr1: 'App-Name',
    expr2: 'permaNewsfeed'
  }
}

**Comment by AndreiD** [comment]
added it! thank you for your submission
